"""Orchestration for .vel, CSS, Python, and deployment-file generation."""

from pathlib import Path
from backend.security.workspace_policy import contained
from backend.services.project_service import _project_dir


def _escape(value: object) -> str:
    return str(value or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _render_elements(model: dict) -> str:
    elements = {item.get("id"): item for item in model.get("elements", []) if isinstance(item, dict)}
    roots = [item for item in model.get("elements", []) if isinstance(item, dict) and not item.get("parentId")]
    def render(item: dict) -> str:
        tag = {"heading": "h1", "text": "p", "button": "button", "image": "img", "section": "section", "card": "article"}.get(item.get("type"), "div")
        content = _escape(item.get("text", ""))
        if tag == "img": content = ""
        children = "".join(render(elements[child]) for child in item.get("children", []) if child in elements)
        attrs = " class=\"studio-element studio-{}\"".format(_escape(item.get("type", "block")))
        if tag == "button": attrs += ' type="button"'
        if tag == "img": attrs += ' alt="Generated image"'
        return f"<{tag}{attrs}>{content}{children}</{tag}>"
    return "\n".join(render(item) for item in roots)


def _render_bindings(model: dict) -> str:
    lines = []
    for index, binding in enumerate(model.get("bindings", [])):
        method = str(binding.get("method", "GET")).upper()
        path = str(binding.get("path", "/api/data"))
        function_name = "generated_api_" + str(index)
        body = repr(binding.get("response", {"ok": True, "data": []}))
        lines.extend([f'@app.{method.lower()}({path!r})', f'async def {function_name}():', f'    return {body}', ""])
    return "\n".join(lines)


def generate_project(model: dict) -> dict:
    root = _project_dir(model["id"])
    page = (model.get("pages") or [{"file": "static/js/pages/Home.vel", "name": "Home"}])[0]
    page_file = page.get("file", "static/js/pages/Home.vel")
    page_path = contained(root, root / page_file)
    page_path.parent.mkdir(parents=True, exist_ok=True)
    title = model.get("name", "Flaxon App")
    page_path.write_text(f'''<template>\n  <main class="page-shell">\n    {_render_elements(model)}\n  </main>\n</template>\n''', encoding="utf-8")
    (root / "static" / "js").mkdir(parents=True, exist_ok=True)
    (root / "static" / "js" / "App.vel").write_text("<script>\nimport Home from './pages/Home.vel'\n</script>\n<template><Home /></template>\n", encoding="utf-8")
    (root / "static" / "css").mkdir(parents=True, exist_ok=True)
    (root / "static" / "css" / "app.css").write_text(":root{font-family:system-ui,sans-serif;color:#eef2ff;background:#0b1020}body{margin:0}.page-shell{padding:4rem;max-width:70rem;margin:auto}\n", encoding="utf-8")
    binding_routes = _render_bindings(model)
    (root / "app.py").write_text(f'''from flaxon import Flaxon\n\napp = Flaxon("generated-flaxon-app")\n\n@app.get("/api/health")\nasync def health():\n    return {{"ok": True}}\n\n{binding_routes}\n''', encoding="utf-8")
    (root / "templates").mkdir(exist_ok=True)
    (root / "templates" / "index.html").write_text("<!doctype html><html><body><main id=\"app\"></main><script type=\"module\" src=\"/assets/static/js/App.js\"></script></body></html>\n", encoding="utf-8")
    (root / "requirements.txt").write_text("flaxon\nteloce-py\n", encoding="utf-8")
    (root / "teloce.config.json").write_text('{"staticDir":"static","entry":"static/js/App.vel","outputDir":"public"}\n', encoding="utf-8")
    (root / "vercel.json").write_text('{"buildCommand":"python build.py","outputDirectory":"public","functions":{"api/index.py":{"maxDuration":10}}}\n', encoding="utf-8")
    (root / "README.md").write_text(f"# {title}\n\nGenerated by Teloce Studio.\n\n```bash\npython -m venv .venv\npip install -r requirements.txt\npython build.py\npython -m flaxon run app:app\n```\n", encoding="utf-8")
    return {"ok": True, "projectId": model["id"], "files": [str(path.relative_to(root)).replace("\\", "/") for path in sorted(root.rglob("*")) if path.is_file()]}
