"""Orchestration for .vel, CSS, Python, and deployment-file generation."""

from pathlib import Path
from backend.security.workspace_policy import contained
from backend.services.project_service import _project_dir


def generate_project(model: dict) -> dict:
    root = _project_dir(model["id"])
    page = (model.get("pages") or [{"file": "static/js/pages/Home.vel", "name": "Home"}])[0]
    page_file = page.get("file", "static/js/pages/Home.vel")
    page_path = contained(root, root / page_file)
    page_path.parent.mkdir(parents=True, exist_ok=True)
    title = model.get("name", "Flaxon App")
    page_path.write_text(f'''<template>\n  <main class="page-shell">\n    <h1>{title}</h1>\n    <p>Generated by Teloce Studio.</p>\n  </main>\n</template>\n''', encoding="utf-8")
    (root / "static" / "js").mkdir(parents=True, exist_ok=True)
    (root / "static" / "js" / "App.vel").write_text("<script>\nimport Home from './pages/Home.vel'\n</script>\n<template><Home /></template>\n", encoding="utf-8")
    (root / "static" / "css").mkdir(parents=True, exist_ok=True)
    (root / "static" / "css" / "app.css").write_text(":root{font-family:system-ui,sans-serif;color:#eef2ff;background:#0b1020}body{margin:0}.page-shell{padding:4rem;max-width:70rem;margin:auto}\n", encoding="utf-8")
    (root / "app.py").write_text('''from flaxon import Flaxon\n\napp = Flaxon("generated-flaxon-app")\n\n@app.get("/api/health")\nasync def health():\n    return {"ok": True}\n''', encoding="utf-8")
    (root / "templates").mkdir(exist_ok=True)
    (root / "templates" / "index.html").write_text("<!doctype html><html><body><main id=\"app\"></main><script type=\"module\" src=\"/assets/static/js/App.js\"></script></body></html>\n", encoding="utf-8")
    (root / "requirements.txt").write_text("flaxon\nteloce-py\n", encoding="utf-8")
    return {"ok": True, "projectId": model["id"], "files": [str(path.relative_to(root)).replace("\\", "/") for path in sorted(root.rglob("*")) if path.is_file()]}
